### ISSUE TITLE
README.md needs an update

### ISSUE THREAD

**Issue by featherwit** [wiserain/docker-flexget#10]
Port described in the document is 3539.
WebUI (v2) default port is 5050.

**Comment by wiserain** [comment]
Could you let me know where I can find it officially? Document says 8080 in https://flexget.com/Web-UI

**Comment by featherwit** [comment]
> 
> 
> Could you let me know where I can find it? Official document says 8080 in https://flexget.com/Web-UI

https://flexget.com/Web-UI
> web_server Usage
> This is the simple configuration that uses default values. It will enable the API and web UI at http://0.0.0.0:5050/v2 (IP 0.0.0.0, port 5050) by default.

**Comment by wiserain** [comment]
My mistake. Please check https://github.com/wiserain/docker-flexget/commit/24611d1c809b3b3cb1621040e5c7f3f313f02f1f.
