### ISSUE TITLE
Exec format error on Synology NAS after the last update

### ISSUE THREAD

**Issue by obionex-5** [wiserain/docker-flexget#14]
I use this image on a Synology NAS and it worked great. 

About 2 days ago this image stopped working with the following error:
standard_init_linux.go:222: exec user process caused "exec format error

**Comment by wiserain** [comment]
Couldn't find any problem. Please try with a container by recreating it.

**Comment by obionex-5** [comment]
Tag 3.1.72 works without any issues. The latest has this strange issue.

**Comment by wiserain** [comment]
Please provide more information. At least running environment, log, docker command you tried to create container. Or I will close this.

**Comment by obionex-5** [comment]
Not sure what exactly was the problem but after several attempts of creating/deleting containers it's working with the same settings as before and on the latest tag.
