### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by badkernel** [wiserain/docker-flexget#15]
Hello 

There is an issue with password setup.
I added "somepassword" in to 
-e FG_WEBUI_PASSWD=<desired password> \
but when I connect to flexget via web:5050 it gives me this msg:
"If this is your first time running the WebUI you need to set a password via the command line by running `flexget web passwd <new_password>`"

Please advise

**Comment by wiserain** [comment]
What image are you using? How is container log message from `docker logs`?

**Comment by badkernel** [comment]
Its latest version from docker hub
and here is log msg
020-12-21 15:37:35 WARNING  web_server                    No password set for web server, create one by using `flexget web passwd <password>`

**Comment by wiserain** [comment]
How about setting it manually by `docker exec <your_container name or id> flexget web passwd <your own passwd>`?

**Comment by badkernel** [comment]
cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
Removing lockfile
Using existing config.yml
Setting flexget web password to 'somepassword'
Oops, something went wrong
Flexget v3.1.91 ready!
[cont-init.d] 20-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services

**Comment by badkernel** [comment]
Thank you it did the trick.
Please add this to your manual on the docker hub website and also comment that 
one must create complex password
Works now!

**Comment by wiserain** [comment]
Quoting envs may help the problem, like `-e "FG_WEBUI_PASSWD=your_own_passwd"`

**Comment by badkernel** [comment]
Issue was I belive anyway that I used simple password but in reality it asked for more complex:

docker exec flexget flexget web passwd somepassword
There is a FlexGet process already running for this config, sending execution there.
Password 'somepassword' is not strong enough. Suggestions: Add another word or two. Uncommon words are better.

**Comment by wiserain** [comment]
> Issue was that I used simple password but in reality it asked for more complex:

Oh, I see. Thanks. I will fix it.
