### ISSUE TITLE
Timezone setting does not work.

### ISSUE THREAD

**Issue by terrellgf** [wiserain/docker-flexget#19]
![image](https://user-images.githubusercontent.com/54665471/104353927-6cb67a00-5543-11eb-867b-cfb6cc0bb337.png)
![image](https://user-images.githubusercontent.com/54665471/104354004-88218500-5543-11eb-92df-54142fd46694.png)
![image](https://user-images.githubusercontent.com/54665471/104354112-b010e880-5543-11eb-9322-2edea81273e5.png)

**Comment by wiserain** [comment]
I have no idea what cause the problem. It might be an incomplete implementation or a bug in webui.

**Comment by terrellgf** [comment]
> I have no idea what cause the problem. It might be an incomplete implementation or a bug in webui.

Does this web service seem to be implemented in python? Maybe it only imported datetime and not pytz?
Could the cause of the problem be this: 
https://stackoverflow.com/questions/7065164/how-to-make-an-unaware-datetime-timezone-aware-in-python

**Comment by wiserain** [comment]
There's nothing I can do for this issue. Please file an issue to the official Flexget repository. They design, implement, and organize everything. https://github.com/Flexget/Flexget/issues

**Comment by terrellgf** [comment]
> There's nothing I can do for this issue. Please file an issue to the official Flexget repository. They design, implement, and organize everything. https://github.com/Flexget/Flexget/issues

I got it. Ths!

**Comment by terrellgf** [comment]
I have to file for this issue to the official Flexget repository.
