### ISSUE TITLE
How to add curl command

### ISSUE THREAD

**Issue by PDSCi996** [wiserain/docker-flexget#21]
Thank you very much for mirroring.
I now want to use flexget to cooperate with youtube-dl to automatically download youtube videos, and I have automatically grabbed the updated rss, but the log prompts "Stdout: /bin/sh: curl: not found" when pushing, and I checked that the possible reason is that the mirror is not found. Caused by the curl command.
Since I don't know much about docker, I would like to ask how to install or package curl commands into the image you made.

**Comment by wiserain** [comment]
Move into docker container by ```docker exec -it <container name or hash id> bash``` then type command ```apk add --no-cache curl``` to install curl. However, this will be removed/roll-backed if you recreate the container. 

If you want this to be persist, 1) make your own docker image, 2) use docker commit, or 3) use cont.init-d. The last one is described in [README.md](https://github.com/wiserain/docker-flexget#additional-packages)

**Comment by PDSCi996** [comment]
> Move into docker container by ```docker exec -it <container name or hash id> bash``` then type command ```apk add --no-cache curl``` to install curl. However, this will be removed/roll-backed if you recreate the container. 
> 
> 
> 
> If you want this to be persist, 1) build your own docker image with packages you wish to include , 2) use docker commit feature, or 3) use cont.init-d. The last one is described in [README.md](https://github.com/wiserain/docker-flexget#additional-packages)

Thank you very much for your help, the problem has been solved, I manually installed the curl command in the container.
