### ISSUE TITLE
Error: missing torrent_info_hash

### ISSUE THREAD

**Issue by harveyphan** [wiserain/docker-flexget#22]
Hi,

I am using docker flexget with docker rutorrent on synology, and facing this issue: missing torrent_info_hash.

My config:
tvshows:
    rtorrent:
      uri: scgi://localhost:5000
      custom2: tvshows
      path: /tv/{{ series_name }}/Season {{ series_season }}/
    include: [ series.yml ]
    disable: builtins
    metainfo_series: yes
    tmdb_lookup: yes

Am I missing something?

Thanks

**Comment by wiserain** [comment]
Please provide more infos like docker tag you are using now and flexget version, and flexget logs.

**Comment by harveyphan** [comment]
Hi wiserain,

I am using:
- Your flexget docker, latest version up to now.
- Rutorrent docker, latest version as well.

Flexget log:
- tracker A:
2021-02-06 19:39:46 CRITICAL plugin        trackerA          Couldn't connect to rTorrent: [Errno 111] Connection refused
2021-02-06 19:39:46 WARNING  task          trackerA          Aborting task (plugin: rtorrent)

with http
021-02-06 10:59:08 CRITICAL plugin        trackerA          Couldn't connect to rTorrent: HTTPConnectionPool(host='192.168.50.46', port=32995): Max retries exceeded with url: /RPC2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6afc56b7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

- tracker B: 
Failed torrent (missing torrent_info_hash)

I think 2 dockers cannot connect to each other, and I don't know how can make it work.

Many thanks

**Comment by wiserain** [comment]
1. rutorrent ip address 192.168.50.46 is correct?
2. are they in different network so they cannot communicate each other?
3. any of containers using vpn?

Command used for docker run/create or docker-compose.yml for figure out the problem as well.

**Comment by harveyphan** [comment]
Hi.
1. yes, rutorrent ip address is 192.168.50.46.
docker image: https://github.com/linuxserver/docker-rutorrent
2. they are on the same network (Synology).
3. No VPN at all.

About the rutorrent image, its used port 5000 for scgi port, but it conflict with Synology default port. So I mapped 50000:5000.
The rutorret is working perfectly fine so far, only I cannot make it work with flexget.

Thanks

**Comment by harveyphan** [comment]
Hi again

I just restart both dockers, and now seeing this error

`    |    -> <function RTorrentOutputPlugin.add_entry at 0x7f6b00b98310>
stdout
13:32:08
    -> <flexget.plugins.clients.rtorrent.RTorrentOutputPlugin object at 0x7f6b00269250>
stdout
13:32:08
  File "/usr/lib/python3.8/site-packages/flexget/plugins/clients/rtorrent.py", line 634, in add_entry
stdout
13:32:08
    if client.torrent(entry['torrent_info_hash']):
stdout
13:32:08
       |      |       -> <Entry(title=Druk 2020 1080p BluRay DD+5.1 x264-iFT,state=accepted)>
stdout
13:32:08
       |      -> <function RTorrent.torrent at 0x7f6b00b96b80>
stdout
13:32:08
       -> <flexget.plugins.clients.rtorrent.RTorrent object at 0x7f6afc6b8430>
stdout
13:32:08
  File "/usr/lib/python3.8/site-packages/flexget/plugins/clients/rtorrent.py", line 305, in torrent
stdout
13:32:08
    resp = multi_call()
stdout
13:32:08
           -> <MultiCall at 0x7f6afc55e6d0>
stdout
13:32:08
  File "/usr/lib/python3.8/xmlrpc/client.py", line 879, in __call__
stdout
13:32:08
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
stdout
13:32:08
           |                 |                              -> [{'methodName': 'd.hash', 'params': ('6F8B9CAF22A8873D6DCEA80E325AB3B83ADFA9C1',)}, {'methodName': 'd.name', 'params': ('6F8B...
stdout
13:32:08
           |                 -> <MultiCall at 0x7f6afc55e6d0>
stdout
13:32:08
           -> <class 'xmlrpc.client.MultiCallIterator'>
stdout
13:32:08
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
stdout
13:32:08
    return self.__send(self.__name, args)
stdout
13:32:08
           |           |            -> ([{'methodName': 'd.hash', 'params': ('6F8B9CAF22A8873D6DCEA80E325AB3B83ADFA9C1',)}, {'methodName': 'd.name', 'params': ('6F8...
stdout
13:32:08
           |           -> <xmlrpc.client._Method object at 0x7f6afc817d90>
stdout
13:32:08
           -> <xmlrpc.client._Method object at 0x7f6afc817d90>
stdout
13:32:08
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
stdout
13:32:08
    response = self.__transport.request(
stdout
13:32:08
               -> <ServerProxy for 192.168.50.46:50000/RPC2>
stdout
13:32:08
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
stdout
13:32:08
    return self.single_request(host, handler, request_body, verbose)
stdout
13:32:08
           |    |              |     |        |             -> False
stdout
13:32:08
           |    |              |     |        -> b"<?xml version='1.0'?>\n<methodCall>\n<methodName>system.multicall</methodName>\n<params>\n<param>\n<value><array><data>\n<v...
stdout
13:32:08
           |    |              |     -> '/RPC2'
stdout
13:32:08
           |    |              -> '192.168.50.46:50000'
stdout
13:32:08
           |    -> <function SCGITransport.single_request at 0x7f6b00b96820>
stdout
13:32:08
           -> <flexget.plugins.clients.rtorrent.SCGITransport object at 0x7f6affd49d60>
stdout
13:32:08
  File "/usr/lib/python3.8/site-packages/flexget/plugins/clients/rtorrent.py", line 144, in single_request
stdout
13:32:08
    return self.parse_response(response_body)
stdout
13:32:08
           |    |              -> <_io.BytesIO object at 0x7f6afc6d0090>
stdout
13:32:08
           |    -> <function Transport.parse_response at 0x7f6b01e6d820>
stdout
13:32:08
           -> <flexget.plugins.clients.rtorrent.SCGITransport object at 0x7f6affd49d60>
stdout
13:32:08
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1339, in parse_response
stdout
13:32:08
    p.close()
stdout
13:32:08
    | -> <function ExpatParser.close at 0x7f6b01e69310>
stdout
13:32:08
    -> <xmlrpc.client.ExpatParser object at 0x7f6afcbf3e50>
stdout
13:32:08
  File "/usr/lib/python3.8/xmlrpc/client.py", line 447, in close
stdout
13:32:08
    parser.Parse(b"", True) # end of data
stdout
13:32:08
    |      -> <method 'Parse' of 'pyexpat.xmlparser' objects>
stdout
13:32:08
    -> <pyexpat.xmlparser object at 0x7f6afc8deca0>
stdout
13:32:08
stdout
13:32:08
xml.parsers.expat.ExpatError: no element found: line 1, column 0
stdout
13:32:08
2021-02-06 20:32:08 CRITICAL manager              An unexpected crash has occurred. Writing crash report to /config/crash_report.2021.02.06.203208176367.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.102
stdout
13:32:08
2021-02-06 20:32:08 WARNING  task `

**Comment by harveyphan** [comment]
I use https, but got this ssl error
Caused by SSLError(SSLCertVerificationErr
or(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate

configuration:
movies:
    rtorrent:
      uri: https://192.168.50.46:5443
      username: '{? deluge.username ?}'
      password: '{? deluge.password ?}'
      path: /downloads/movies/
      custom1: movies

**Comment by harveyphan** [comment]
Ok, so if I turn off authentication for rutorrent and use http only, then everything works.

Many thanks

**Comment by wiserain** [comment]
Sounds great!

**Comment by harveyphan** [comment]
Hi,

Just want to let you know that the movie tracker is working fine, but not the tvshow tracker.

I am facing this error for the tv tracker: (missing torrent_info_hash)

Thanks
