### ISSUE TITLE
Issue: missing torrent_info_hash

### ISSUE THREAD

**Issue by harveyphan** [wiserain/docker-flexget#23]
Hi,

Sorry to recreating this issue, as it happened again. Please could you have a look?
My environment:

- Synology
- Flexget docker: latest tag.
- Error: (missing torrent_info_hash)

Thanks

**Comment by wiserain** [comment]
Sorry for the late reply. Please provide minimal settings so I can reproduce the issue. Then, I will have a look if it still persist.

**Comment by harveyphan** [comment]
Hi,

It's fine. I swapped to qbittorrent and everything is working good.

Thanks
