### ISSUE TITLE
Behaviour of flexget docker

### ISSUE THREAD

**Issue by kokare-darshan** [wiserain/docker-flexget#35]
I just wanted to know if this docker is active all time for we need to setup cron job to start flexget (like every 30 min)

if docker is active all time, can we make it to exit whenever flexget finishes its job. so everyone can save machine's resources

**Comment by paulpoco** [comment]
If you look at the log file, then very 1st thing it does is show
![image](https://user-images.githubusercontent.com/801414/136710764-1428df45-287a-4519-b9a5-3b3b90c0a60f.png)
