### ISSUE TITLE
Chown on /data and /config dirs

### ISSUE THREAD

**Issue by gurg1e** [wiserain/docker-flexget#36]
Hey on startup this tries to chown the /data and /config directories, and fails if it cannot. Is there a way to not do this? I have my dirs bind-mounted from a NFS share with _all_squash_ flag, meaning that the user and group cannot be changed. 

Thanks

**Comment by wiserain** [comment]
Hope 3cbdeb10493f929f3b3b1b55272b8eb3b295321c helps
