### ISSUE TITLE
Updating to 3.1.130 (fixes broken plugin)

### ISSUE THREAD

**Issue by obionex-5** [wiserain/docker-flexget#37]
Hi!

Any chance this will be updated to 3.1.130? There is a major bug regarding lostfilm plugin in the older versions of Flexget.
Thanks!

**Comment by zankevich** [comment]
@obionex-5 While we waiting you can use my fork https://hub.docker.com/r/zankevich/flexget.

**Comment by obionex-5** [comment]
> @obionex-5 While we waiting you can use my fork https://hub.docker.com/r/zankevich/flexget.

Great! Will you support it in the future? Current project seems to be on the slower side of updates.

**Comment by zankevich** [comment]
> > @obionex-5 While we waiting you can use my fork https://hub.docker.com/r/zankevich/flexget.
> 
> Great! Will you support it in the future? Current project seems to be on the slower side of updates.

I don't have plans to support but I have exact same problem with LostFilm :) and if there are new problems with version I will update.

**Comment by Zloi78** [comment]
> 
> 
> > > @obionex-5 While we waiting you can use my fork https://hub.docker.com/r/zankevich/flexget.
> > 
> > 
> > Great! Will you support it in the future? Current project seems to be on the slower side of updates.
> 
> I don't have plans to support but I have exact same problem with LostFilm :) and if there are new problems with version I will update.

I use Flexget and Jacket in this case. There are no problems with Lostfilm.
