### ISSUE TITLE
Maybe the script in /config/custom-cont-init.d should be executed before flexget runs when the container starts ?

### ISSUE THREAD

**Issue by Oscar1011** [wiserain/docker-flexget#48]
I made a script in /config/custom-cont-init.d to install pip requirements. and put some plugins in flexget.
If I recreate the docker container. it fails to start and reports missing requirements

**Comment by Oscar1011** [comment]
I mean execute the script before flexget runs

**Comment by wiserain** [comment]
Executing flexget for setting password in `/etc/cont-init.d/20-config` might cause missing requirements error when fresh container startup. 

If that's the case, you should not declare top-level import for the dependencies in your plugin script. It is recommended having local imports in each necessary function like we implemented [here](https://github.com/wiserain/docker-flexget/blob/master/root/defaults/plugins/write_magnet.py).

**Comment by Oscar1011** [comment]
thank you
