### ISSUE TITLE
Docker container couldn't start

### ISSUE THREAD

**Issue by machsix** [wiserain/docker-flexget#53]
I tested tags 3.3.7 and 3.3.6 for linux/amd64. Docker log stucks at 
```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
*** Using existing config.yml
*** Setting flexget web password
Updated password
```
for both versions.

I need to override the file `/etc/cont-init.d/20-config` by removing the last line
```
echo "*** Flexget v$(flexget -V | sed -n 1p) ready!"
```

The command `flexget -V` never returns. I'm not sure if it's something wrong on my side. A clean config.yaml doesn't help

**Comment by wiserain** [comment]
Tested and working fine for me.
