### ISSUE TITLE
Container stops with an error about missing /scripts/init.sh

### ISSUE THREAD

**Issue by sarbian** [wiserain/docker-flexget#7]
The last version (3.1.45) does not start properly. There is an error about a missing /scripts/init.sh

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
Using existing config.yml
Flexget v3.1.45 ready!
[cont-init.d] 20-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] executing => flexget -c /config/config.yml --loglevel info daemon start --autoreload-config
[services.d] done.
ifelse: fatal: unable to exec /scripts/init.sh: No such file or directory
[cmd] /scripts/init.sh exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by wiserain** [comment]
Can you please try without CMD directives?

**Comment by sarbian** [comment]
I do not have a CMD in my compose file. But it worked after I restarted it with docker-compose.
It seems that what I use to keep the image updated ( Ouroboros ) kept the cmd when it upgraded the images. 
Anyway it works and it was on my side. Sorry for the superfluous ticket.
