### ISSUE TITLE
Need to install convert_magnet.py manually?

### ISSUE THREAD

**Issue by sentience** [wiserain/docker-flexget#8]
This repo contains a version of `convert_magnet.py` that is compatible with the latest libtorrent (introduced in 4da5de84b57544518c8b990873c53e0010bcb082). As far as I can tell, there is no automatic installation of this plugin baked into this image, so if you want to use this plugin, you need to find this repo, find the plugin, and copy it into your /config/plugins directory.

Would it be desirable to automate its installation, or at least document how to install it in the image README? Happy to contribute something.

**Comment by wiserain** [comment]
At the time of writing modified version of convert_magnet.py, it is for your reference. Wasn't so sure it can override builtin one without any troubles. I will try to containerize it, or at least document as suggested. Thanks.

**Comment by wiserain** [comment]
@sentience Please find it sorted in https://github.com/wiserain/docker-flexget/commit/cee92d9c3a24ac1b9dede25f459e02b7f48be30d. Updated ```write_magnet``` plugin, formerly ```convert_magnet```, needs some test though.
