### ISSUE TITLE
cannot work on N1, N1 os is 小钢炮

### ISSUE THREAD

**Issue by looker201314** [wiserain/docker-flexget#9]
create docker command:
docker run -d \
    --name=flexget \
    -p 3539:3539 \
    -v /media/HOME/flexget/data:/data \
    -v /media/HOME/flexget/config:/config \
    -e FG_WEBUI_PASSWD=admin \
    -e FG_LOG_LEVEL=info \
    -e PUID=0 \
    -e PGID=0 \
    -e TZ=Asia/Shanghai \
    wiserain/flexget

log：
[root@phicomm-n1:~]# docker logs flexget
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
Removing lockfile
Using existing config.yml
Setting flexget web password to 'admin'
Oops, something went wrong

docker exec flexget flexget web passwd adminadmin
Log:
attached file
[putty_135_20200606232257.log](https://github.com/wiserain/docker-flexget/files/4740523/putty_135_20200606232257.log)

**Comment by wiserain** [comment]
There might be a problem with migrating flexget database. Try to use an old version .

**Comment by looker201314** [comment]
> There might be a problem with migrating flexget database. Try to use an old version .

Thanks.
wiserain/flexget:3.1.51 is the first version for arm64. And I try this version and get the same error with the latest version.

**Comment by wiserain** [comment]
Couldn't find any problem with clean install (starting with empty ```/config``` dir) in the latest arm64 image.

**Comment by looker201314** [comment]
I am sorry. Now I also run flexget sucessfully with clean /config dir.

Two days ago, firstly I create docker with non-existent uid and gid, and didnot clean /config dir.
Next I create docker with uid 0 and gid 0, and failed because /config dir is dirty
